### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by namjae**
added update/2 for updating by other column name than 'id' (the hard coded name).

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.chef.io/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## Non-GitHub Verified Committers

There are 1 commit author(s) whose commits are authored by a non-GitHub verified email address. Chef will have to manually verify that they are authorized to contribute.

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by seth** [comment]
Thanks for the PR. This looks like a reasonable addition to me. If you're willing to sign the CLA, then next step would be to squash this into a single commit and add a small test.

**Comment by marcparadise** [comment]
@namjae I know it's been a while - but if you're still interested in closing this out, a CLA is no longer required - we have moved to a DCO[1] policy instead. 
You can update your PR with this as follows:
```
git checkout develop
git commit --amend -S --no-edit
git push -f
```

Once that is done, I can add a test for this case and get the PR merged.

[1] http://developercertificate.org/

**Comment by marcparadise** [comment]
I am closing this for now, @namjae please re-open if you're able to update your PR with the DCO signooff.

**Pull request closed without merging**
